version: '2.3'

services:
  model:
    container_name: de-id_model
    build:
      context: ./
      dockerfile: docker/dockerfile_model
    runtime: nvidia
    restart: always
    ipc: "host"
    env_file:
      - "docker/dockerenv.env"
    volumes:
      - type: volume
        source: dataset
        target: /dataset
        volume:
          nocopy: true
    ports:
      - "8022:22"
      - "8000:8000"
      - "8001:8001"
      - "8888:8888"
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Seoul
volumes:
  dataset:
    driver: local
    driver_opts:
      type: none
      device: "/media/hdd"
      o: bind