version: '2.3'

services:
  model:
    container_name: de-id_model
    build:
      context: ./
      dockerfile: docker/model/dockerfile
    runtime: nvidia
    restart: always
    ipc: "host"
    env_file:
      - "docker/model/dockerenv.env"
    volumes:
      - /media/mmlab/hdd:/hdd
      - type: volume
        source: dataset
        target: /dataset
        volume:
          nocopy: true
      - type: volume
        source: mldisk_shared
        target: /mldisk_shared
        volume:
          nocopy: true
      - type: volume
        source: mldisk_shared_
        target: /mldisk_shared_
        volume:
          nocopy: true
      - type: volume
        source: mldisk2
        target: /mldisk2
        volume:
          nocopy: true
      - type: volume
        source: mlsun
        target: /mlsun
        volume:
          nocopy: true
    ports:
      - "10022:22"
      - "18000:8000"
      - "18001:8001"
      - "18888:8888"
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Seoul
  disc:
    container_name: de-id_model
    build:
      context: ./
      dockerfile: docker/model/dockerfile
    runtime: nvidia
    restart: always
    ipc: "host"
    env_file:
      - "docker/model/dockerenv.env"
    volumes:
      - /media/mmlab/hdd:/hdd
      - type: volume
        source: dataset
        target: /dataset
        volume:
          nocopy: true
      - type: volume
        source: mldisk_shared
        target: /mldisk_shared
        volume:
          nocopy: true
      - type: volume
        source: mldisk_shared_
        target: /mldisk_shared_
        volume:
          nocopy: true
      - type: volume
        source: mldisk2
        target: /mldisk2
        volume:
          nocopy: true
      - type: volume
        source: mlsun
        target: /mlsun
        volume:
          nocopy: true
    ports:
      - "20022:22"
      - "28000:8000"
      - "28001:8001"
      - "28888:8888"
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Seoul

volumes:
  dataset:
    driver: local
    driver_opts:
      type: none
      device: "/home/mmlab/dataset/deid"
      o: bind
  mldisk_shared:
    driver_opts:
      type: "nfs"
      o: "addr=mldisk.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume1/nfs_shared"
  mldisk_shared_:
    driver_opts:
      type: "nfs"
      o: "addr=mldisk.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume3/nfs_shared_"
  mldisk2:
    driver_opts:
      type: "nfs"
      o: "addr=mldisk2.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume1/nfs_shared"
  mlsun:
    driver_opts:
      type: "nfs"
      o: "addr=mlsun.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume1/nfs_shared"