version: '2.3'

services:
  main:
    container_name: de-id_main
    build:
      context: ./
      dockerfile: docker/Dockerfile
    runtime: nvidia
    restart: always
    ipc: "host"
    env_file:
      - "docker/dockerenv.env"
    volumes:
      - /media/mmlab/hdd:/hdd
      - type: volume
        source: mldisk_shared
        target: /mldisk_shared
        volume:
          nocopy: true
      - type: volume
        source: mldisk_shared_
        target: /mldisk_shared_
        volume:
          nocopy: true
      - type: volume
        source: mldisk2
        target: /mldisk2
        volume:
          nocopy: true
      - type: volume
        source: mlsun
        target: /mlsun
        volume:
          nocopy: true
    ports:
      - "18000:8000"
      - "18888:8000"
      - "10022:22"
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Seoul

volumes:
  mldisk_shared:
    driver_opts:
      type: "nfs"
      o: "addr=mldisk.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume2/nfs_shared"
  mldisk_shared_:
    driver_opts:
      type: "nfs"
      o: "addr=mldisk.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume3/nfs_shared_"
  mldisk2:
    driver_opts:
      type: "nfs"
      o: "addr=mldisk2.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume1/nfs_shared"
  mlsun:
    driver_opts:
      type: "nfs"
      o: "addr=mlsun.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume1/nfs_shared"