FROM nvidia/cuda:11.7.0-cudnn8-devel-ubuntu20.04

RUN apt-get update && apt-get -y install \
    python3 python3-pip python3-dev \
    libgl1 tzdata git wget ssh vim

WORKDIR /workspace
ADD . .

RUN pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
RUN pip install -r docker/requirements.txt