infer:
  device: 1
  model:
    face:
      model_name: yolov7
      model_path: /workspace/model/weights/yolov7-w6-face.pt
      device: 0
      image_size: 1280
      conf_thresh: 0.1
      batch_size: 16
      iou_thresh: 0.5
    feature:
      model_name: S2VC
      model_path: ""
      input_size: 224
    inverter:
      model_name: ResNet50UNetInverter
      model_path: ''
      input_size: 224
train:
  device: 0
  master_addr: localhost
  master_port: "8001"
  batch_size: 2
  epoch: 200
  valid_epoch: 5
  learning_rate: 0.0002
  decay_epoch: 100
  dataset_dir: /dataset/widerface/deepfake_resize
  save_dir: /dataset/cyclegan_widerface_vcd/
  model:
    feature:
      model_name: S2VC
      feature_weight_path: /workspace/model/weights/pca_resnet50_vcdb_1M.pth
      input_size: 224
    cyclegan:
      model_name: ResNetD2GAN
      resume: false
      pretrained_model_dir: /dataset/cyclegan_model/20230923_140447_ResNetCycleGAN/weights/
      b1: 0.5
      b2: 0.999
      input_size: 256
      channels: 3
      residual_block_number: 9
  lambda:
    lambda_cycle: 5.0
    lambda_identity: 10.0
    lambda_full_image: 10.0
  wandb:
    project_name: CycleGAN
    account: jinhasong