infer:
  device: 0
  model:
    feature:
      model_name: ResNet50
      model_path: /workspace/model/weights/sscd_disc_mixup.torchvision.pt
      input_size: 224
    inverter:
      model_name: ResNet50UNetInverter
      model_path: /hdd/feature_inversion/20230712_185154_ResNet50UNetInverter/weights/epoch_000015.pth
      input_size: 224
train:
  device: 3
  master_addr: 0.0.0.0
  master_port: "8000"
  batch_size: 128
  learning_rate: 0.0001
  epoch: 100
  dataset_dir: /dataset/dna/inversion
  save_dir: /dataset/feature_inversion_dna/
  decay_epoch: 50
  valid_epoch: 5
  model:
    feature:
      model_name: ResNet50
      feature_weight_path: /workspace/model/weights/sscd_disc_mixup.torchvision.pt
      input_size: 224
    inverter:
      model_name: ResNet50UNetInverter
      input_size: 224
      resume: false
      pretrained_model_path: ''
  lambda:
    feature_mse: 0.1
    feature_cosine: 0.7
    region_mse: 0.2
  wandb:
    project_name: FeatureInversion
    account: jinhasong