infer:
  device: 2
  model:
    face:
      model_name: yolov7
      model_path: /workspace/model/weights/yolov7-w6-face.pt
      device: 2
      image_size: 1280
      conf_thresh: 0.1
      batch_size: 16
      iou_thresh: 0.5
    feature:
      model_name: MobileNet_AVG
      model_path: /workspace/model/weights/mobilenet_avg_ep16_ckpt.pth
      input_size: 224
    inverter:
      model_name: ResNet50UNetInverter
      model_path: /dataset/feature_inversion_dna/20231008_012013_ResNet50UNetInverter/weights/epoch_000081.pth
      input_size: 224
train:
  device: 0
  master_addr: 0.0.0.0
  master_port: "8000"
  batch_size: 40
  learning_rate: 0.0001
  epoch: 100
  dataset_dir: /dataset/images_1080/
  save_dir: /hdd/feature_inversion/
  decay_epoch: 50
  valid_epoch: 5
  model:
    feature:
      model_name: MobileNet_AVG
      feature_weight_path: /workspace/model/weights/mobilenet_avg_ep16_ckpt.pth
      input_size: 224
    inverter:
      model_name: ResNet50UNetInverter
      input_size: 224
      resume: true
      pretrained_model_path: /hdd/feature_inversion/20230712_185154_ResNet50UNetInverter/weights/epoch_000030.pth
  lambda:
    feature_mse: 1
    feature_cosine: 1
    region_mse: 1
  wandb:
    project_name: FeatureInversion
    account: jinhasong