det:
  face:
    yolov5:
      model_name: yolov5m-face
      model_path: /workspace/model/weights/yolov5m-face.pt
      device: 0
      image_size: 640
      conf_thresh: 0.3
      iou_thresh: 0.5
    yolov7:
      model_name: yolov7-w6-face
      model_path: /workspace/model/weights/yolov7-w6-face.pt
      device: 0
      image_size: 1280
      conf_thresh: 0.3
      iou_thresh: 0.5