infer:
  device: 0
  model:
    feature:
      model_name: ResNet50
      model_path: /workspace/model/weights/sscd_disc_mixup.torchvision.pt
      input_size: 224
    inverter:
      model_name: MobileUNetInverter
      model_path: /hdd/feature_inversion/20230712_185154_ResNet50UNetInverter/weights/epoch_000015.pth
      input_size: 224
train:
  device: 3
  master_addr: localhost
  master_port: "8001"
  batch_size: 128
  learning_rate: 0.0001
  epoch: 200
  dataset_dir: /dataset/vggface2hq_refine
  save_dir: /dataset/resnet50_inverter_vggface2/
  decay_epoch: 100
  valid_epoch: 5
  model:
    feature:
      model_name: ResNet50
      feature_weight_path: /workspace/model/weights/sscd_disc_mixup.torchvision.pt
      input_size: 224
    inverter:
      model_name: ResNet50Inverter
      input_size: 224
      resume: false
      pretrained_model_path: ''
  lambda:
    feature_mse: 0.1
    feature_cosine: 0.7
    region_mse: 0.2
  wandb:
    project_name: FeatureInversion
    account: jinhasong
