infer:
  device: 0
  model_name: ResNet50UNetInverter
  input_size: 224
  model_path: /hdd/feature_inversion/20230712_185154_ResNet50UNetInverter/weights/epoch_000030.pth
train:
  device: 1
  master_addr: 0.0.0.0
  master_port: "8000"
  batch_size: 40
  learning_rate: 0.0001
  epoch: 100
  dataset_dir: /dataset/images/
  save_dir: /hdd/feature_inversion/
  valid_epoch: 5
  model:
    feature:
      model_name: ResNet50
      feature_weight_path: /workspace/model/weights/sscd_disc_mixup.torchvision.pt
      input_size: 224
    inverter:
      model_name: ResNet50UNetInverter
      input_size: 224
      resume: true
      pretrained_model_path: /hdd/feature_inversion/20230917_160515_ResNet50UNetInverter/weights/epoch_000007.pth
  lambda:
    feature_mse: 1
    feature_cosine: 1
    region_mse: 1
  wandb:
    project_name: FeatureInversion
    account: jinhasong